# apiVersion: v1
# kind: Service
# metadata:
#   name: my-app-service
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80         # External port
#     targetPort: 8080  # Port on the container
#   selector:
#     app: my-app




apiVersion: v1
kind: Service
metadata:
  name: my-app
  annotations:
    cloud.google.com/load-balancer-type: "External"  # This annotation configures the service as an Internal Load Balancer
spec:
  type: LoadBalancer
  ports:
    - port: 80                # The port that will be exposed externally
      targetPort: 3000        # The port on the pod that the traffic will be directed to
      protocol: TCP
  selector:
    app: my-app       # This should match the labels of your pods
