apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80         # External port
    targetPort: 8080  # Port on the container
  selector:
    app: my-app
